# Generated by Django 4.0.6 on 2022-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_ordering', models.IntegerField()),
                ('novel', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-book_ordering',),
            },
        ),
    ]
